version: '3'
services:
  web:
    build: .
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./custom_addons:/mnt/extra-addons
